archiveArtifacts artifacts: '**/build.log'
After seeing failures due to
```
Archiving artifacts
‘.moderne/build/**/build.log’ doesn’t match anything, but ‘**/build.log’ does. Perhaps that’s what you mean?
Error when executing always post condition:
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: ad746932-9e4f-4851-9929-05cbf0b3209d
hudson.AbortException: No artifacts found that match the file pattern ".moderne/build/**/build.log". Configuration error?
```
https://jenkins.moderne.ninja/view/Maven/job/cli-ingest/job/apache_maven-ejb-plugin_master/lastFailedBuild/console

Could have been temporary due to the normalization issues, but at least this way it should still match.